## POSTTEST 4(DATA PREPROCESSING)

# IMPORT PACKAGE
- Pandas
- Numpy
- Scikit-Learn(Sklearn)

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# untuk Data Split
from sklearn.model_selection import train_test_split #testing dan training data
# untuk Data Transforming
from sklearn.preprocessing import StandardScaler #standarisasi
from sklearn.preprocessing import MinMaxScaler #normalisasi
# untuk Data Cleaning
from sklearn.impute import SimpleImputer #subtitusi nilai
# untuk Data Encoding
from sklearn.preprocessing import OrdinalEncoder #encoder
from sklearn.preprocessing import OneHotEncoder #onehot

import warnings
warnings.filterwarnings('ignore')

## Record File "patient.csv"

In [2]:
df = pd.read_csv('patient.csv')
df.head()

patient_id  gender   age nationality     province current_state  \
0           1  female  31.0   indonesia  DKI Jakarta      released   
1           2  female  64.0   indonesia  DKI Jakarta      released   
2           3  female  33.0   indonesia  DKI Jakarta      released   
3           4  female  34.0   indonesia  DKI Jakarta      isolated   
4           5    male  55.0   indonesia  DKI Jakarta      isolated   

   contacted_with confirmed_date released_date deceased_date  \
0             NaN       2-Mar-20     13-Mar-20           NaN   
1             1.0       2-Mar-20     16-Mar-20           NaN   
2             1.0       6-Mar-20     13-Mar-20           NaN   
3             1.0       6-Mar-20           NaN           NaN   
4             1.0       8-Mar-20           NaN           NaN   

               hospital  
0  RSPI Sulianti Saroso  
1  RSPI Sulianti Saroso  
2  RSPI Sulianti Saroso  
3  RSPI Sulianti Saroso  
4       RS Persahabatan

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   patient_id      893 non-null    int64  
 1   gender          156 non-null    object 
 2   age             156 non-null    float64
 3   nationality     156 non-null    object 
 4   province        156 non-null    object 
 5   current_state   166 non-null    object 
 6   contacted_with  27 non-null     float64
 7   confirmed_date  893 non-null    object 
 8   released_date   5 non-null      object 
 9   deceased_date   4 non-null      object 
 10  hospital        17 non-null     object 
dtypes: float64(2), int64(1), object(8)
memory usage: 76.9+ KB


In [4]:
df.isna().sum()

patient_id          0
gender            737
age               737
nationality       737
province          737
current_state     727
contacted_with    866
confirmed_date      0
released_date     888
deceased_date     889
hospital          876
dtype: int64

In [5]:
print(f'panjang dataset {len(df)} baris')

panjang dataset 893 baris


## Record File "cases.csv"

In [6]:
df2 = pd.read_csv('cases.csv')
df2.head()

date  new_tested  acc_tested  new_confirmed  acc_confirmed  \
0  2-Mar-20         NaN         339              2              2   
1  3-Mar-20         2.0         341              0              2   
2  4-Mar-20        31.0         372              0              2   
3  5-Mar-20        16.0         388              0              2   
4  6-Mar-20        62.0         450              2              4   

   acc_negative  being_checked  isolated  new_released  acc_released  \
0           335              2         2             0             0   
1           337              2         2             0             0   
2           356             14         2             0             0   
3           371             15         2             0             0   
4           422             24         4             0             0   

   new_deceased  acc_deceased positive_rate negative_rate decease_rate  \
0             0             0         0.59%        98.82%        0.00%   
1             0             0         0.59%        98.83%        0.00%   
2             0             0         0.54%        95.70%        0.00%   
3             0             0         0.52%        95.62%        0.00%   
4             0             0         0.89%        93.78%        0.00%   

  release_rate dailypositive_rate  
0        0.00%              0.00%  
1        0.00%              0.00%  
2        0.00%              0.00%  
3        0.00%              0.00%  
4        0.00%              3.23%

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   date                30 non-null     object 
 1   new_tested          28 non-null     float64
 2   acc_tested          30 non-null     int64  
 3   new_confirmed       30 non-null     int64  
 4   acc_confirmed       30 non-null     int64  
 5   acc_negative        30 non-null     int64  
 6   being_checked       30 non-null     int64  
 7   isolated            30 non-null     int64  
 8   new_released        30 non-null     int64  
 9   acc_released        30 non-null     int64  
 10  new_deceased        30 non-null     int64  
 11  acc_deceased        30 non-null     int64  
 12  positive_rate       30 non-null     object 
 13  negative_rate       30 non-null     object 
 14  decease_rate        30 non-null     object 
 15  release_rate        30 non-null     object 
 16  dailyposit

In [8]:
df2.isna().sum()

date                  0
new_tested            2
acc_tested            0
new_confirmed         0
acc_confirmed         0
acc_negative          0
being_checked         0
isolated              0
new_released          0
acc_released          0
new_deceased          0
acc_deceased          0
positive_rate         0
negative_rate         0
decease_rate          0
release_rate          0
dailypositive_rate    0
dtype: int64

In [9]:
print(f'panjang dataset {len(df2)} baris')

panjang dataset 30 baris


## Record File "charts.csv"

In [10]:
df3 = pd.read_csv('charts.csv')
df3.head()

date  rank           song                         artist  last-week  \
0  2021-11-06     1     Easy On Me                          Adele        1.0   
1  2021-11-06     2           Stay  The Kid LAROI & Justin Bieber        2.0   
2  2021-11-06     3  Industry Baby        Lil Nas X & Jack Harlow        3.0   
3  2021-11-06     4     Fancy Like                   Walker Hayes        4.0   
4  2021-11-06     5     Bad Habits                     Ed Sheeran        5.0   

   peak-rank  weeks-on-board  
0          1               3  
1          1              16  
2          1              14  
3          3              19  
4          2              18

In [11]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330087 entries, 0 to 330086
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   date            330087 non-null  object 
 1   rank            330087 non-null  int64  
 2   song            330087 non-null  object 
 3   artist          330087 non-null  object 
 4   last-week       297775 non-null  float64
 5   peak-rank       330087 non-null  int64  
 6   weeks-on-board  330087 non-null  int64  
dtypes: float64(1), int64(3), object(3)
memory usage: 17.6+ MB


In [12]:
df3.isna().sum()

date                  0
rank                  0
song                  0
artist                0
last-week         32312
peak-rank             0
weeks-on-board        0
dtype: int64

In [13]:
print(f'panjang dataset {len(df3)} baris')

panjang dataset 330087 baris


## Record File "songs_normalize.csv"

In [14]:
df4 = pd.read_csv('songs_normalize.csv')
df4.head()

artist                    song  duration_ms  explicit  year  \
0  Britney Spears  Oops!...I Did It Again       211160     False  2000   
1       blink-182    All The Small Things       167066     False  1999   
2      Faith Hill                 Breathe       250546     False  1999   
3        Bon Jovi            It's My Life       224493     False  2000   
4          *NSYNC             Bye Bye Bye       200560     False  2000   

   popularity  danceability  energy  key  loudness  mode  speechiness  \
0          77         0.751   0.834    1    -5.444     0       0.0437   
1          79         0.434   0.897    0    -4.918     1       0.0488   
2          66         0.529   0.496    7    -9.007     1       0.0290   
3          78         0.551   0.913    0    -4.063     0       0.0466   
4          65         0.614   0.928    8    -4.806     0       0.0516   

   acousticness  instrumentalness  liveness  valence    tempo         genre  
0        0.3000          0.000018    0.3550    0.894   95.053           pop  
1        0.0103          0.000000    0.6120    0.684  148.726     rock, pop  
2        0.1730          0.000000    0.2510    0.278  136.859  pop, country  
3        0.0263          0.000013    0.3470    0.544  119.992   rock, metal  
4        0.0408          0.001040    0.0845    0.879  172.656           pop

In [15]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   artist            2000 non-null   object 
 1   song              2000 non-null   object 
 2   duration_ms       2000 non-null   int64  
 3   explicit          2000 non-null   bool   
 4   year              2000 non-null   int64  
 5   popularity        2000 non-null   int64  
 6   danceability      2000 non-null   float64
 7   energy            2000 non-null   float64
 8   key               2000 non-null   int64  
 9   loudness          2000 non-null   float64
 10  mode              2000 non-null   int64  
 11  speechiness       2000 non-null   float64
 12  acousticness      2000 non-null   float64
 13  instrumentalness  2000 non-null   float64
 14  liveness          2000 non-null   float64
 15  valence           2000 non-null   float64
 16  tempo             2000 non-null   float64


In [16]:
df4.isna().sum()

artist              0
song                0
duration_ms         0
explicit            0
year                0
popularity          0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
genre               0
dtype: int64

In [17]:
print(f'panjang dataset {len(df4)} baris')

panjang dataset 2000 baris


## Record File "Transformed Data Set - Sheet1.csv"

In [18]:
df5 = pd.read_csv('Transformed Data Set - Sheet1.csv')
df5.head()

Favorite Color Favorite Music Genre Favorite Beverage Favorite Soft Drink  \
0           Cool                 Rock             Vodka          7UP/Sprite   
1        Neutral              Hip hop             Vodka     Coca Cola/Pepsi   
2           Warm                 Rock              Wine     Coca Cola/Pepsi   
3           Warm     Folk/Traditional           Whiskey               Fanta   
4           Cool                 Rock             Vodka     Coca Cola/Pepsi   

  Gender  
0      F  
1      F  
2      F  
3      F  
4      F

In [19]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Favorite Color        66 non-null     object
 1   Favorite Music Genre  66 non-null     object
 2   Favorite Beverage     66 non-null     object
 3   Favorite Soft Drink   66 non-null     object
 4   Gender                66 non-null     object
dtypes: object(5)
memory usage: 2.7+ KB


In [20]:
df5.isna().sum()

Favorite Color          0
Favorite Music Genre    0
Favorite Beverage       0
Favorite Soft Drink     0
Gender                  0
dtype: int64

In [21]:
print(f'panjang dataset {len(df5)} baris')

panjang dataset 66 baris


## Record File "tangsel_covid19.csv"

In [22]:
df6 = pd.read_csv('tangsel_covid19.csv')
df6.head()

Unnamed: 0  ODP  PDP  POSITIF  SEMBUH  MENINGGAL
0  3/26/2020  204   89       17       0          4
1  3/27/2020  207   99       17       0          4
2  3/29/2020  256  119       28       0          4
3  3/30/2020  262  123       31       0          6
4  3/31/2020  308  134       34       2          6

In [23]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  14 non-null     object
 1   ODP         14 non-null     int64 
 2   PDP         14 non-null     int64 
 3   POSITIF     14 non-null     int64 
 4   SEMBUH      14 non-null     int64 
 5   MENINGGAL   14 non-null     int64 
dtypes: int64(5), object(1)
memory usage: 800.0+ bytes


In [24]:
df6.isna().sum()

Unnamed: 0    0
ODP           0
PDP           0
POSITIF       0
SEMBUH        0
MENINGGAL     0
dtype: int64

In [25]:
print(f'panjang dataset {len(df6)} baris')

panjang dataset 14 baris


## DATA SPLIT
Train/test split adalah salah satu metode yang dapat digunakan untuk
mengevaluasi performa model machine learning. Metode evaluasi model ini
membagi dataset menjadi dua bagian yakni bagian yang digunakan untuk training
data dan untuk testing data dengan proporsi tertentu.

In [26]:
data = df[['contacted_with']]
label = df['hospital']

data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=.3)

In [27]:
print(f'panjang data training {len(data_train)}',
     f'panjang label training {len(label_train)}',
     f'panjang data testing {len(data_test)}',
     f'panjang label testing {len(label_test)}',
     sep='\n')

panjang data training 625
panjang label training 625
panjang data testing 268
panjang label testing 268


## DATA TRANSFORMASI
Transformasi data adalah merubah skala data kedalam bentuk lain sehingga
data memiliki distribusi yang diharapkan.Scaling adalah suatu cara untuk membuat
numerical data pada dataset memiliki rentang nilai (scale) yang sama. Tidak ada lagi
satu variabel data yang mendominasi variabel data lainnya.Teknik penskalaan yang
biasa dipakai yaitu normalisasi dan standardisasi
- Normalisasi adalah proses penskalaan data menjadi rentang [0, 1].
- Standardisasi adalah proses penskalaan data sehingga memiliki nilai rata-rata 0 dan standar deviasi 1.

In [28]:
dataset_normalisasi = df3.copy()
dataset_standarirasi = df6.copy()

NORMALISASI

In [29]:
scaler = MinMaxScaler()

normalize_dataset = scaler.fit_transform(dataset_normalisasi[['last-week', 'peak-rank', 'weeks-on-board']])

normalize_dataset = pd.DataFrame(normalize_dataset)
normalize_dataset.rename(columns={ 0 :'last-week', 1 : 'peak-rank', 2 : 'weeks-on-board'}, inplace=True)

normalize_dataset.head(5)

last-week  peak-rank  weeks-on-board
0   0.000000   0.000000        0.022472
1   0.010101   0.000000        0.168539
2   0.020202   0.000000        0.146067
3   0.030303   0.020202        0.202247
4   0.040404   0.010101        0.191011

STANDARISASI

In [30]:
dataset_standarirasi.drop('Unnamed: 0', axis=1, inplace=True)   # axis=1 == column | axis=0 == row | inplace=True == do the execution without reassign

standart_std = StandardScaler()

scaled_data = standart_std.fit_transform(dataset_standarirasi)

print('Dataset sebelum scalling:',  # SEBELUM
      df6.drop('Unnamed: 0', axis=1).head(6),
      f'Nilai standar deviasi:\n{np.std(df6)}',
      sep='\n', end='\n\n')

print('Dataset setelah scalling:',  # SESUDAH
      scaled_data[:6],
      f'Nilai standar deviasi: {np.std(scaled_data)}',
      sep='\n')

Dataset sebelum scalling:
   ODP  PDP  POSITIF  SEMBUH  MENINGGAL
0  204   89       17       0          4
1  207   99       17       0          4
2  256  119       28       0          4
3  262  123       31       0          6
4  308  134       34       2          6
5  336  139       38       2          6
Nilai standar deviasi:
ODP          154.028489
PDP           51.682903
POSITIF       10.369697
SEMBUH         2.171241
MENINGGAL      4.616408
dtype: float64

Dataset setelah scalling:
[[-1.36523909 -1.53131602 -1.97002591 -0.92113237 -1.25329348]
 [-1.34576217 -1.33782844 -1.97002591 -0.92113237 -1.25329348]
 [-1.02763921 -0.95085327 -0.90924273 -0.92113237 -1.25329348]
 [-0.98868537 -0.87345824 -0.61993822 -0.92113237 -0.82005623]
 [-0.69003932 -0.66062189 -0.33063372  0.         -0.82005623]
 [-0.50825477 -0.5638781   0.05510562  0.         -0.82005623]]
Nilai standar deviasi: 0.9999999999999999


## DATA CLEANING
Data yang kita gunakan bisa jadi sangat berantakan. Ada informasi yang tak
lengkap, ada pula format yang berbeda-beda.Semua ini tentu membuat data itu sulit
diolah. Pada akhirnya, ia jadi tak bisa dimanfaatkan. Untuk itulah kita harus
melakukan data cleaning terlebih dahulu. Data cleaning adalah memperbarui,
membetulkan, dan membuat data menjadi lebih rapi. Beberapa model machine
learning tidak dapat bekerja dengan data yang masih berantakan. Kesalahan dalam
data dapat berupa:
- Terdapat nilai data yang tidak valid (Null)
- Data dalam format yang salah
- Terdapat duplikat

In [31]:
dataset_ns = df3.copy()
dataset_ns2 = df2.copy()
dataset_ns3 = df.copy()

In [32]:
imputer_mean = SimpleImputer(strategy='mean')
imputer_median = SimpleImputer(strategy='median')
imputer_modus = SimpleImputer(strategy='most_frequent')

MODUS

In [33]:
dataset_ns['last-week'] = imputer_modus.fit_transform(dataset_ns[['last-week']])

dataset_ns.isna().sum()

date              0
rank              0
song              0
artist            0
last-week         0
peak-rank         0
weeks-on-board    0
dtype: int64

MEAN

In [34]:
dataset_ns2['new_tested'] = imputer_mean.fit_transform(dataset_ns2[['new_tested']])

dataset_ns2.isna().sum()

date                  0
new_tested            0
acc_tested            0
new_confirmed         0
acc_confirmed         0
acc_negative          0
being_checked         0
isolated              0
new_released          0
acc_released          0
new_deceased          0
acc_deceased          0
positive_rate         0
negative_rate         0
decease_rate          0
release_rate          0
dailypositive_rate    0
dtype: int64

Menghapus record/feature

In [35]:
dataset_ns3.dropna(inplace=True)

dataset_ns3.isna().sum()

patient_id        0.0
gender            0.0
age               0.0
nationality       0.0
province          0.0
current_state     0.0
contacted_with    0.0
confirmed_date    0.0
released_date     0.0
deceased_date     0.0
hospital          0.0
dtype: float64

In [36]:
len(dataset_ns)

330087

DATA DUPLIKAT

In [37]:
dataset_duplicate = df4.copy()

dataset_duplicate.duplicated().sum()

59

In [38]:
dataset_duplicate.drop_duplicates(inplace=True)

dataset_duplicate.duplicated().sum()

0

## ENCODING
Encoding adalah salah tahap pre-processing ketika kita menghadapi data
yang bersifat kategorikal. Encoding adalah teknik yang mengubah variabel
kategorikal menjadi variabel numerik, model dalam machine learning membutuhkan
input yang bertipe numerik sehingga sangat penting bagi kita untuk melakukan
encoding jika terdapat variabel yang bertipe kategorikal didalam data kita. Teknik
encoding yang paling terkenal adalah Ordinal Encoding dan One-Hot Encoding

In [39]:
dataset_ordinal = df5.copy()
dataset_one_hot = df5.copy()

In [40]:
df5['Gender'].unique()

array(['F', 'M'], dtype=object)

ORDINAL

In [41]:
encoder_ordinal =OrdinalEncoder()

#encoding kan
dataset_ordinal['Gender'] = encoder_ordinal.fit_transform(dataset_ordinal[['Gender']]).astype('int64')

#lihat
dataset_ordinal.head()

Favorite Color Favorite Music Genre Favorite Beverage Favorite Soft Drink  \
0           Cool                 Rock             Vodka          7UP/Sprite   
1        Neutral              Hip hop             Vodka     Coca Cola/Pepsi   
2           Warm                 Rock              Wine     Coca Cola/Pepsi   
3           Warm     Folk/Traditional           Whiskey               Fanta   
4           Cool                 Rock             Vodka     Coca Cola/Pepsi   

   Gender  
0       0  
1       0  
2       0  
3       0  
4       0

In [42]:
dataset_ordinal['Gender'].unique()

array([0, 1], dtype=int64)

ONE-HOT

In [43]:
temp_dataset = pd.get_dummies(dataset_one_hot[['Gender']])

temp_dataset = pd.DataFrame(temp_dataset)

dataset_one_hot.drop('Gender', axis=1, inplace=True)

dataset_one_hot = dataset_one_hot.join(temp_dataset)
dataset_one_hot.head(5)

Favorite Color Favorite Music Genre Favorite Beverage Favorite Soft Drink  \
0           Cool                 Rock             Vodka          7UP/Sprite   
1        Neutral              Hip hop             Vodka     Coca Cola/Pepsi   
2           Warm                 Rock              Wine     Coca Cola/Pepsi   
3           Warm     Folk/Traditional           Whiskey               Fanta   
4           Cool                 Rock             Vodka     Coca Cola/Pepsi   

   Gender_F  Gender_M  
0         1         0  
1         1         0  
2         1         0  
3         1         0  
4         1         0