## POSTTEST 7(TENSORFLOW BASIC)

## IMPORT PACKAGE
- TensorFlow
- Numpy

In [1]:
import tensorflow as tf
import numpy as np

## 1. Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1., seed=1)
random_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

In [3]:
list_utt = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]

utt = tf.convert_to_tensor(list_utt)
utt.numpy()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
slicing = tf.random.normal([5,5,5])
slicing.numpy()

array([[[-0.79880553,  0.25166914, -0.1579376 ,  0.42878348,
         -0.8968296 ],
        [ 0.46129006,  1.2953346 ,  0.00305816,  0.81140965,
          0.2492997 ],
        [-0.17737526, -0.14885277, -1.3904814 , -1.4573394 ,
          0.47839355],
        [-0.6414622 ,  0.09378263,  0.20713314,  0.22633255,
          0.9253177 ],
        [-0.11254343,  0.826041  , -0.70456517,  0.49581617,
         -0.10243657]],

       [[-0.18765259, -2.0469024 , -2.5204253 ,  0.70996314,
          0.83468914],
        [ 2.686354  ,  0.70958036,  1.2024552 , -0.9448725 ,
          0.61680096],
        [ 2.1156259 ,  0.58247316, -0.85841846,  1.5118393 ,
         -0.93162435],
        [-1.528792  ,  0.23050943,  0.2460423 , -0.63239366,
         -0.01131425],
        [-0.9792384 ,  0.31620026, -0.6969196 ,  1.0452522 ,
         -2.4430866 ]],

       [[ 1.2692382 ,  0.35944098,  0.21286167,  0.05459456,
          0.06272434],
        [-1.3099172 , -0.16106665,  0.09859801,  0.19170673,
          0

In [5]:
slicing[2,2,2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.87577146>

In [6]:
slicing[2]

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.2692382 ,  0.35944098,  0.21286167,  0.05459456,  0.06272434],
       [-1.3099172 , -0.16106665,  0.09859801,  0.19170673,  0.48581913],
       [ 0.58744365,  0.6805352 ,  0.87577146, -1.89278   ,  1.7697693 ],
       [-1.5970249 , -0.74799055, -0.47635016,  1.2088494 , -0.5233485 ],
       [-2.5603554 , -2.5237627 , -1.2801988 ,  0.96558875, -0.0493499 ]],
      dtype=float32)>

In [7]:
tf.gather(slicing, indices=[2,2,2]).numpy()

array([[[ 1.2692382 ,  0.35944098,  0.21286167,  0.05459456,
          0.06272434],
        [-1.3099172 , -0.16106665,  0.09859801,  0.19170673,
          0.48581913],
        [ 0.58744365,  0.6805352 ,  0.87577146, -1.89278   ,
          1.7697693 ],
        [-1.5970249 , -0.74799055, -0.47635016,  1.2088494 ,
         -0.5233485 ],
        [-2.5603554 , -2.5237627 , -1.2801988 ,  0.96558875,
         -0.0493499 ]],

       [[ 1.2692382 ,  0.35944098,  0.21286167,  0.05459456,
          0.06272434],
        [-1.3099172 , -0.16106665,  0.09859801,  0.19170673,
          0.48581913],
        [ 0.58744365,  0.6805352 ,  0.87577146, -1.89278   ,
          1.7697693 ],
        [-1.5970249 , -0.74799055, -0.47635016,  1.2088494 ,
         -0.5233485 ],
        [-2.5603554 , -2.5237627 , -1.2801988 ,  0.96558875,
         -0.0493499 ]],

       [[ 1.2692382 ,  0.35944098,  0.21286167,  0.05459456,
          0.06272434],
        [-1.3099172 , -0.16106665,  0.09859801,  0.19170673,
          0

In [8]:
tf.gather_nd(slicing, indices=[[0,2],[1,2],[2,2],[3,2],[4,2]]).numpy()

array([[-0.17737526, -0.14885277, -1.3904814 , -1.4573394 ,  0.47839355],
       [ 2.1156259 ,  0.58247316, -0.85841846,  1.5118393 , -0.93162435],
       [ 0.58744365,  0.6805352 ,  0.87577146, -1.89278   ,  1.7697693 ],
       [ 0.19295204, -0.7963113 , -0.50165117,  0.19448532, -1.2694831 ],
       [ 1.0702144 , -2.5726328 , -1.9871469 , -1.8193521 , -0.5939659 ]],
      dtype=float32)

In [9]:
tf.gather_nd(slicing, indices=[[0,2,2],[1,2,2],[2,2,2],[3,2,2],[4,2,2]]).numpy()

array([-1.3904814 , -0.85841846,  0.87577146, -0.50165117, -1.9871469 ],
      dtype=float32)

## 2. Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [10]:
list_prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

prime_tensor = tf.constant(list_prime, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

## 3. Tampilkan dimensi dari kedua variable tersebut

In [11]:
random_tensor.shape

TensorShape([5, 5])

In [12]:
prime_tensor.shape

TensorShape([5, 5])

## 4. Tampilkan hasil dari perhitungan aritmatika 2 variable tersebut (Gunakan minimal 5 operator)

In [13]:
print("1. Penjumlahan :",tf.add(prime_tensor,random_tensor))
print("\n2. Pengurangan :",tf.subtract(prime_tensor,random_tensor))
print("\n3. Perkalian :",tf.multiply(prime_tensor,random_tensor))
print("\n4. Pembagian :",tf.divide(prime_tensor,random_tensor))
print("\n5. Pangkat :",tf.pow(prime_tensor,random_tensor))
print("\n6. FloorDiv :",tf.math.floordiv(prime_tensor,random_tensor))
print("\n7. FloorMod :",tf.math.floormod(prime_tensor,random_tensor))
print("\n8. Greater :",tf.math.greater(prime_tensor,random_tensor))
print("\n9. Setara :",tf.equal(prime_tensor,random_tensor))
print("\n10. Tidak Setara :",tf.not_equal(prime_tensor,random_tensor))
print("\n11. Greater Equal :",tf.math.greater_equal(prime_tensor,random_tensor))
print("\n12. Less :",tf.math.less(prime_tensor,random_tensor))
print("\n13. Less Equal :",tf.math.less_equal(prime_tensor,random_tensor))
print("\n14. Maximum :",tf.math.maximum(prime_tensor,random_tensor))
print("\n15. Minimum :",tf.math.minimum(prime_tensor,random_tensor))
print("\n16. Kuadrat Perbedaan :",tf.math.squared_difference(prime_tensor,random_tensor))
print("\n17. TrueDiv :",tf.math.truediv(prime_tensor,random_tensor))
print("\n18. XdivY :",tf.math.xdivy(prime_tensor,random_tensor))
print("\n19. Xlog1pY :",tf.math.xlog1py(prime_tensor,random_tensor))
print("\n20. XlogY :",tf.math.xlogy(prime_tensor,random_tensor))
print("\n21. Atan2 :",tf.math.atan2(prime_tensor,random_tensor))

1. Penjumlahan : tf.Tensor(
[[ 1.1886818  4.4845986  5.0653296  4.557296  11.099248 ]
 [13.591225  17.592823  16.877071  22.277103  28.94373  ]
 [31.643545  36.735676  42.856632  43.56784   46.617165 ]
 [51.514656  60.261772  60.974693  70.73537   74.532814 ]
 [77.25702   82.5621    88.43399   97.32067    2.132831 ]], shape=(5, 5), dtype=float32)

2. Pengurangan : tf.Tensor(
[[ 2.8113182   1.5154012   4.9346704   9.442704   10.900752  ]
 [12.408775   16.407177   21.122929   23.722897   29.05627   ]
 [30.356455   37.264324   39.143368   42.43216    47.382835  ]
 [54.485344   57.738228   61.025307   71.26463    71.467186  ]
 [80.74298    83.4379     89.56601    96.67933    -0.13283098]], shape=(5, 5), dtype=float32)

3. Perkalian : tf.Tensor(
[[  -1.6226364     4.4537964     0.32664686  -17.09893       1.0917324 ]
 [   7.685916     10.077991    -40.335663    -16.626637     -1.6318411 ]
 [  19.949888     -9.77999      76.12196      24.417194    -17.993286  ]
 [ -78.7232       74.444496   

## 5. Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [14]:
tf.argmax(random_tensor, axis=0).numpy()#max baris random_tensor

array([2, 0, 2, 2, 3], dtype=int64)

In [15]:
tf.argmax(random_tensor, axis=1).numpy()#max kolom random_tensor

array([1, 1, 2, 4, 4], dtype=int64)

In [16]:
tf.argmin(random_tensor, axis=0).numpy()#min baris random_tensor

array([4, 4, 1, 0, 2], dtype=int64)

In [17]:
tf.argmin(random_tensor, axis=1).numpy()#min kolom random_tensor

array([3, 2, 4, 0, 0], dtype=int64)

## 6. Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [18]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()#penggabungan baris

array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
         1.0000000e+00]], dtype=float32)

In [19]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy()#penggabungan kolom

array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0000000e+00]], dtype=float32)

## 7. Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [20]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[ 1.4845988 ,  0.0992484 ,  0.06532937, -0.8113182 , -2.4427042 ],
       [ 0.59282297,  0.5912243 , -0.05627038, -0.72289723, -2.1229296 ],
       [ 1.8566332 ,  0.6435448 ,  0.5678417 , -0.26432407, -0.3828359 ],
       [ 1.5328138 ,  1.2617711 , -0.02530608, -0.2646297 , -1.4853433 ],
       [ 1.132831  ,  0.32066926, -0.43789294, -0.56601   , -1.7429771 ]],
      dtype=float32)

In [21]:
sort_random_tensor2 = tf.argsort(random_tensor, direction="DESCENDING")
sort_random_tensor2.numpy()

array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])

In [22]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)

In [23]:
sort_prime_tensor2 = tf.argsort(prime_tensor, direction="DESCENDING")
sort_prime_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])